version: '3'

networks:
  1panel-network:
    external: true

services:

  db-migrate:
    image: ghcr.io/hcd233/aris-api-tmpl:master # aris-api-tmpl:latest
    container_name: db-migrate
    restart: no
    networks:
      - 1panel-network
    env_file:
      - ../env/api.env
    command: ["/app/aris-api-tmpl", "database", "migrate"]

  aris-api-tmpl:
    image: ghcr.io/hcd233/aris-api-tmpl:master # aris-api-tmpl:latest
    container_name: aris-api-tmpl
    restart: always
    networks:
      - 1panel-network
    ports:
      - 8170:8080
    env_file:
      - ../env/api.env
    depends_on:
      db-migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

    command: ["/app/aris-api-tmpl", "server", "start", "--host", "0.0.0.0", "--port", "8080"]

# docker compose -f docker/docker-compose-without-middlewares.yml up -d
